name: Terraform CI/CD

on:
  workflow_dispatch:  
  push:
    branches: [ main ] 

permissions:
  id-token: write       # required for OIDC
  contents: read

env:
  AWS_REGION: sa-east-1 
  TF_WORKING_DIR: infrastructure
  YML_ENVIROMENT: development
  TF_VAR_db_username: ${{ secrets.DB_USERNAME }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }} 

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    name: "Terraform Plan"
    environment: development

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/flow-ai-role-github-actions
          aws-region: ${{ env.AWS_REGION }}
          role-session-name: github-actions-flow-ai-session

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init -input=false

      - name: Terraform Plan
        id: plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform plan -out=plan.tfplan -input=false

      - name: Upload Terraform Plan Artifact
        uses: actions/upload-artifact@v4
        with:
          name: terraform_plan
          path: ${{ env.TF_WORKING_DIR }}/plan.tfplan